spring:
  data:
    mongodb:
      database: health-care-system-collections
      port: 27017
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  
  application:
    name: REPORT-SERVCIE
       
server:
 port: 9601
 
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
