server:
   port: 9600 

spring:
  application:
    name: HOSPITAL-SERVCIE
    
  datasource:
    url: jdbc:mysql://localhost:3306/HealthCare
    username: root
    password: 8210
   
   
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    


  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
