version: "3"

networks:
  employee-net:
  org-net:
  
services:
   
   employee-service:
     image: employee-service:1.0
     container_name: employee-service
     ports:
       - 9595:9595  
     environment: 
       - DB_URL=jdbc:mysql://192.168.224.1:3306/HealthCare?useUnicode=yes&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
       - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-registry:8761/eureka
     networks:
      - employee-net
      
   org-service:
     image: org-service:1.0
     container_name: org-service
     ports:
       - 9596:9596  
     environment: 
       - DB_URL=jdbc:mysql://192.168.224.1:3306/HealthCare?useUnicode=yes&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
       - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-registry:8761/eureka
     networks:
      - org-net  
     
   service-registry:
      image: service-registry:1.0
      container_name: service-registry
      ports:
        - 8761:8761
      networks:
        - employee-net
        - org-net
