spring:
  data:
    mongodb:
      database: health-care-system-collections
      port: 27017
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  application:
    name: APPOINTMENT-SERVICE    

server:
 port: 9598  
#  data:
#    mongodb:
#      database: fdb
#      port: 27017

#eureka:
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka
