server:
  port: 9599
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/HealthCare
    username: root
    password: 8210
    
  application:
    name: AGENCY-SERVICE  
    
  jpa:
    hibernate:
      ddl-auto: update
      
    show-sql: true
    
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
      
#eureka:
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka      